version: "3"

server:
    command: "php public/index.php"
    env:
        APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
        LOG_PATH: php://stderr

metrics:
    address: 0.0.0.0:8081

grpc:
    listen: "tcp://0.0.0.0:9002"
    proto:
        - "./service.proto"
    pool:
        num_workers: 2
        destroy_timeout: 30s
        supervisor:
            exec_ttl: 20s
            max_worker_memory: 100

status:
    address: 0.0.0.0:8082

logs:
    output: stderr
    encoding: json
    level: info
    mode: production

endure:
    grace_period: 30s
