<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace App\Grpc\GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x92\x01\x0A\x0Dservice.proto\x12\x07service\"\x16\x0A\x07Message\x12\x0B\x0A\x03msg\x18\x01 \x01(\x0924\x0A\x04Echo\x12,\x0A\x04Ping\x12\x10.service.Message\x1A\x10.service.Message\"\x00B\"\xCA\x02\x08App\\Grpc\xE2\x02\x14App\\Grpc\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

